query GetLastChatMessages($topic: String!) {
    getLastTwentyMessages(topic: $topic) {
        author {
            givenName
            familyName
        }
        avatar {
            url
        }
        message
        createdAt
    }
}
