subscription SubscribeToChat($topic: String!) {
    subscribeToChat(topic: $topic) {
        author {
            givenName,
            familyName
        }
        avatar {
            url
        }
        message
        date
    }
}
